## Learning Pytorch
References:
* https://towardsdatascience.com/pytorch-tutorial-distilled-95ce8781a89c
* http://adventuresinmachinelearning.com/pytorch-tutorial-deep-learning/
* https://hsaghir.github.io/data_science/pytorch_starter/
* https://jdhao.github.io/2017/11/12/pytorch-computation-graph/
* https://discuss.pytorch.org/t/print-autograd-graph/692/4
* https://medium.com/intuitionmachine/pytorch-dynamic-computational-graphs-and-modular-deep-learning-7e7f89f18d1
* https://github.com/PaddlePaddle/VisualDL

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from __future__ import print_function

### Create Tensors

In [2]:
# Create a matrix 2x2
x = torch.tensor([1, 2])
print('1x2 tensor:')
print(x)
print(x.size())

# Create a matrix 2x2
x = torch.tensor([[1, 2],[3, 4]])
print('\n2x2 tensor:')
print(x)
print(x.size())
print('All rows from first collumn')
# We can have all numpy cool matrix sub-indexing
print(x[:, 0])
print(x[:, 0].size())

## Create unitialized 5x3 tensor
x = torch.empty(5, 3, dtype=torch.long)
print('\nNon-initialized 5x3 tensor:')
print(x)

# Create random 5x3 tensor
x = torch.rand(5, 3)
print('\nRandom 5x3 tensor:')
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
x = torch.ones(5, 3, dtype=torch.double)
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
y= torch.ones(5, 3, dtype=torch.double) * 2
print(y)

1x2 tensor:
tensor([ 1,  2])
torch.Size([2])

2x2 tensor:
tensor([[ 1,  2],
        [ 3,  4]])
torch.Size([2, 2])
All rows from first collumn
tensor([ 1,  3])
torch.Size([2])

Non-initialized 5x3 tensor:
tensor([[ 1.3983e+14,  3.9273e+07,  3.2000e+01],
        [ 4.8000e+01,  3.9316e+07,  4.2950e+09],
        [ 2.5271e+07,  3.9319e+07,  8.0000e+01],
        [ 4.8000e+01,  3.9319e+07,  4.2950e+09],
        [ 2.5271e+07,  3.7298e+07,  1.2800e+02]])

Random 5x3 tensor:
tensor([[ 0.2715,  0.2855,  0.3676],
        [ 0.9996,  0.5161,  0.7803],
        [ 0.0990,  0.1935,  0.9880],
        [ 0.1256,  0.5917,  0.8522],
        [ 0.1361,  0.1929,  0.0387]])

Zeros 5x3 tensor:
tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

Zeros 5x3 tensor:
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

Zeros 5x3 tensor:
tensor([[ 2.,  2.,  2.],
    

### Operations

In [3]:
print(x+y)
print(x*y)
print((x+6)/y)

# Reshape
print(((x+6)/y).view(15))
print(((x+6)/y).view(15).size())
print(((x+6)/y).view(3,5))
print(((x+6)/y).view(3,5).size())

tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.]], dtype=torch.float64)
tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]], dtype=torch.float64)
tensor([[ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000]], dtype=torch.float64)
tensor([ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,
         3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,
         3.5000], dtype=torch.float64)
torch.Size([15])
tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64)
torch.Size([3, 5])


### Numpy Bridge

In [4]:
# Convert torch tensor to numpy
y_numpy = y.numpy()
print(y_numpy)
print(y_numpy.shape)
print(type(y_numpy))

# Convert numpy ndarray to torch
y_torch = torch.from_numpy(y_numpy)
print(y_torch)
print(y_torch.size())
print(type(y_torch))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
(5, 3)
<class 'numpy.ndarray'>
tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]], dtype=torch.float64)
torch.Size([5, 3])
<class 'torch.Tensor'>


### Working with GPU

In [5]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    # Point to your GPU
    device = torch.device("cuda:0") 
    # Move tensor on GPU
    x_gpu = x.to(device)
    y_gpu = y.to(device)
    # Create tensor on GPU
    b_gpu = torch.ones_like(x, device=device) + 3.5
    # Result and the calculation will be on the GPU
    result = x_gpu + y_gpu - b_gpu
    print(result)
    # Move to CPU
    result_cpu = result.to("cpu", torch.double)
    print(result_cpu)

True
tensor([[-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000]], dtype=torch.float64, device='cuda:0')
tensor([[-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000]], dtype=torch.float64)


/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py:116: UserWarning: 
    Found GPU1 Quadro K2000 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


### Autograd

In [6]:
a = torch.ones(1, requires_grad=True)
b = torch.ones(1, requires_grad=True)
c = torch.ones(1, requires_grad=True)
y = ((2*a) * (3*b)) + (4*c)
print(y)
y.backward()
print(y.grad_fn)

tensor([ 10.])


In [7]:
print(a.grad)
print(b.grad)
print(c.grad)

tensor([ 6.])
tensor([ 6.])
tensor([ 4.])


### Simple MLP for XOR problem

In [8]:
class Net(nn.Module):
    # Define the Network structure
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 50)  # 2 Input noses, 50 in middle layers
        self.fc2 = nn.Linear(50, 1)  # 50 middle layer, 1 output nodes
        self.rl1 = nn.ReLU()
        self.rl2 = nn.ReLU()

    # Forward propagation definition
    def forward(self, x):
        x = self.fc1(x)
        x = self.rl1(x)
        x = self.fc2(x)
        x = self.rl2(x)
        return x


In [15]:
net = Net()
print(net)
# Loss and optimization
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.1, momentum=0.1)

trainingdataX = [[[0.01, 0.01], [0.01, 0.90], [0.90, 0.01], [0.95, 0.95]], 
                 [[0.02, 0.03], [0.04, 0.95], [0.97, 0.02], [0.96, 0.95]]]
trainingdataY = [[[0.01], [0.90], [0.90], [0.01]], [[0.04], [0.97], [0.98], [0.1]]]
num_epoch = 20

Net(
  (fc1): Linear(in_features=2, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=1, bias=True)
  (rl1): ReLU()
  (rl2): ReLU()
)


In [16]:
for epoch in range(num_epoch):
    running_loss = 0.0
    for i, data in enumerate(trainingdataX, 0):
        inputs = data
        labels = trainingdataY[i]
        inputs = torch.FloatTensor(inputs)
        labels = torch.FloatTensor(labels)
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        if i % 100 == 0:
            print("loss: ", running_loss)
            running_loss = 0.0

loss:  0.3714306354522705
loss:  0.30153554677963257
loss:  0.24573767185211182
loss:  0.2179236114025116
loss:  0.19900178909301758
loss:  0.18348997831344604
loss:  0.16993379592895508
loss:  0.15774297714233398
loss:  0.14657646417617798
loss:  0.13621646165847778
loss:  0.12556192278862
loss:  0.11756221204996109
loss:  0.10929057002067566
loss:  0.10120408236980438
loss:  0.09167911112308502
loss:  0.08720750361680984
loss:  0.08133243769407272
loss:  0.07495119422674179
loss:  0.06652986258268356
loss:  0.06433743238449097
