## Learning Pytorch
References:
* https://towardsdatascience.com/pytorch-tutorial-distilled-95ce8781a89c
* http://adventuresinmachinelearning.com/pytorch-tutorial-deep-learning/
* https://hsaghir.github.io/data_science/pytorch_starter/
* https://jdhao.github.io/2017/11/12/pytorch-computation-graph/
* https://discuss.pytorch.org/t/print-autograd-graph/692/4
* https://medium.com/intuitionmachine/pytorch-dynamic-computational-graphs-and-modular-deep-learning-7e7f89f18d1
* https://medium.com/init27-labs/pytorch-basics-in-4-minutes-c7814fa5f03d
* https://github.com/PaddlePaddle/VisualDL
* https://www.youtube.com/watch?v=rrekAv9Fml4
* https://www.youtube.com/watch?v=LAMwEJZqesU
* https://github.com/lanpa/tensorboard-pytorch
* https://github.com/lanpa/tensorboard-pytorch-examples

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from __future__ import print_function
import os
from tensorboardX import SummaryWriter
os.environ["CUDA_VISIBLE_DEVICES"] = str(0)

### Create Tensors

In [2]:
# Create a matrix 2x2
x = torch.tensor([1, 2])
print('1x2 tensor:')
print(x)
print(x.size())

# Create a matrix 2x2
x = torch.tensor([[1, 2],[3, 4]])
print('\n2x2 tensor:')
print(x)
print(x.size())
print('All rows from first collumn')
# We can have all numpy cool matrix sub-indexing
print(x[:, 0])
print(x[:, 0].size())

## Create unitialized 5x3 tensor
x = torch.empty(5, 3, dtype=torch.long)
print('\nNon-initialized 5x3 tensor:')
print(x)

# Create random 5x3 tensor
x = torch.rand(5, 3)
print('\nRandom 5x3 tensor:')
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
x = torch.ones(5, 3, dtype=torch.double)
print(x)

# Create 5x3 zeros tensor of type 
print('\nZeros 5x3 tensor:')
y= torch.ones(5, 3, dtype=torch.double) * 2
print(y)

1x2 tensor:
tensor([ 1,  2])
torch.Size([2])

2x2 tensor:
tensor([[ 1,  2],
        [ 3,  4]])
torch.Size([2, 2])
All rows from first collumn
tensor([ 1,  3])
torch.Size([2])

Non-initialized 5x3 tensor:
tensor([[ 1.4053e+14,  1.4053e+14,  3.4360e+10],
        [ 8.3152e+18,  7.0094e+18,  6.6487e+06],
        [ 1.2000e+01,  6.5000e+01,  1.4053e+14],
        [ 1.4053e+14,  3.0065e+10,  1.4053e+14],
        [ 0.0000e+00,  8.0204e+18,  1.2800e+02]])

Random 5x3 tensor:
tensor([[ 0.0863,  0.9402,  0.4183],
        [ 0.9412,  0.4820,  0.1119],
        [ 0.1802,  0.7484,  0.2413],
        [ 0.2143,  0.8955,  0.0017],
        [ 0.4629,  0.8880,  0.3452]])

Zeros 5x3 tensor:
tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

Zeros 5x3 tensor:
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

Zeros 5x3 tensor:
tensor([[ 2.,  2.,  2.],
    

### Operations

In [3]:
print(x+y)
print(x*y)
print((x+6)/y)

# Reshape
print(((x+6)/y).view(15))
print(((x+6)/y).view(15).size())
print(((x+6)/y).view(3,5))
print(((x+6)/y).view(3,5).size())

tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.]], dtype=torch.float64)
tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]], dtype=torch.float64)
tensor([[ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000]], dtype=torch.float64)
tensor([ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,
         3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,
         3.5000], dtype=torch.float64)
torch.Size([15])
tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64)
torch.Size([3, 5])


### Numpy Bridge

In [4]:
# Convert torch tensor to numpy
y_numpy = y.numpy()
print(y_numpy)
print(y_numpy.shape)
print(type(y_numpy))

# Convert numpy ndarray to torch
y_torch = torch.from_numpy(y_numpy)
print(y_torch)
print(y_torch.size())
print(type(y_torch))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
(5, 3)
<class 'numpy.ndarray'>
tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]], dtype=torch.float64)
torch.Size([5, 3])
<class 'torch.Tensor'>


### Working with GPU

In [5]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    # Point to your GPU
    device = torch.device("cuda:0") 
    # Move tensor on GPU
    x_gpu = x.to(device)
    y_gpu = y.to(device)
    # Create tensor on GPU
    b_gpu = torch.ones_like(x, device=device) + 3.5
    # Result and the calculation will be on the GPU
    result = x_gpu + y_gpu - b_gpu
    print(result)
    # Move to CPU
    result_cpu = result.to("cpu", torch.double)
    print(result_cpu)

True
tensor([[-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000]], dtype=torch.float64, device='cuda:0')
tensor([[-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000],
        [-1.5000, -1.5000, -1.5000]], dtype=torch.float64)


### Autograd

In [6]:
a = torch.ones(1, requires_grad=True)
b = torch.ones(1, requires_grad=True)
c = torch.ones(1, requires_grad=True)
y = ((2*a) * (3*b)) + (4*c)
print(y)
y.backward()
print(y.grad_fn)

tensor([ 10.])


In [7]:
print(a.grad)
print(b.grad)
print(c.grad)

tensor([ 6.])
tensor([ 6.])
tensor([ 4.])


### Simple MLP for XOR problem

In [8]:
trainingdataX = [[[0.01, 0.01], [0.01, 0.90], [0.90, 0.01], [0.95, 0.95]], 
                 [[0.02, 0.03], [0.04, 0.95], [0.97, 0.02], [0.96, 0.95]]]
trainingdataY = [[[0.01], [0.90], [0.90], [0.01]], [[0.04], [0.97], [0.98], [0.1]]]
num_epoch = 100

In [9]:
class Net(nn.Module):
    # Add layers
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 50)  # 2 Input noses, 50 in middle layers
        self.fc2 = nn.Linear(50, 1)  # 50 middle layer, 1 output nodes
        self.rl1 = nn.ReLU()
        self.rl2 = nn.ReLU()

    # Define Forward propagation graph
    def forward(self, x):
        x = self.fc1(x)
        x = self.rl1(x)
        x = self.fc2(x)
        x = self.rl2(x)
        return x

In [10]:
# Tensorboard writer
writer = SummaryWriter()

# Create network
net = Net()
print(net)

# Send graph to tensorboard
writer.add_graph(net, torch.rand(4,2))

# Loss (Mean squared error)
criterion = nn.MSELoss()

# Stochastic Gradient Descent Optimizer 
optimizer = optim.SGD(net.parameters(), lr=0.1, momentum=0.1)

Net(
  (fc1): Linear(in_features=2, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=1, bias=True)
  (rl1): ReLU()
  (rl2): ReLU()
)


In [11]:
for epoch in range(num_epoch):
    running_loss = 0.0
    for i, data in enumerate(trainingdataX, 0):
        inputs = data
        labels = trainingdataY[i]
        
        # Convert input/labels to torch tensors
        inputs = torch.FloatTensor(inputs)
        labels = torch.FloatTensor(labels)
        
        # Manually set gradients to zero before the loss.backward() and optimizer.step()
        optimizer.zero_grad()
        
        # Forward Propagation
        outputs = net(inputs)
                
        # Compute loss
        loss = criterion(outputs, labels)
        
        # Compute loss backpropagation
        loss.backward()
        
        # Run optimizer
        optimizer.step()
        
        # Get loss scalar value
        running_loss += loss.item()                
        
        if i % 100 == 0:
            print("loss: ", i, running_loss)
            # Send loss to tensorboard
            writer.add_scalar('loss', running_loss, epoch)
            running_loss = 0.0

# Close summary writer
writer.close()

loss:  0 0.19390258193016052
loss:  0 0.17559272050857544
loss:  0 0.16703534126281738
loss:  0 0.15745577216148376
loss:  0 0.1487674117088318
loss:  0 0.1402340978384018
loss:  0 0.1317737102508545
loss:  0 0.12346547842025757
loss:  0 0.11555860936641693
loss:  0 0.10791541635990143
loss:  0 0.10041213035583496
loss:  0 0.09299322217702866
loss:  0 0.08637244999408722
loss:  0 0.07968957722187042
loss:  0 0.07305885851383209
loss:  0 0.06728613376617432
loss:  0 0.06158054620027542
loss:  0 0.05596209689974785
loss:  0 0.05126432701945305
loss:  0 0.046604834496974945
loss:  0 0.042092807590961456
loss:  0 0.03865436092019081
loss:  0 0.03532835468649864
loss:  0 0.031925275921821594
loss:  0 0.029243800789117813
loss:  0 0.026491202414035797
loss:  0 0.02451477386057377
loss:  0 0.022008556872606277
loss:  0 0.020647196099162102
loss:  0 0.018717125058174133
loss:  0 0.01751130446791649
loss:  0 0.016081802546977997
loss:  0 0.015252402052283287
loss:  0 0.01397533155977726
loss:  